import telebot
from telebot import types
token ='6331366867:AAHW4hx2HKzl35WjdEpxNUVxS087seYMq-k'
bot = telebot.TeleBot(token)
@bot.message_handler(commands=['start'])
def start_message(message):
    bot.send_message(message.chat.id, 'Привет! Ты любишь ВШЭ?👋')
    markup = types.ReplyKeyboardMarkup()
    bt1 = types.KeyboardButton('Да!')
    markup.add(bt1)
    bot.send_message(message.chat.id,'Ну у тебя выбора нет))' ,reply_markup=markup)
@bot.message_handler(content_types=['text'])
def reply(message):
    if message.text =='Да!':
        markup = types.ReplyKeyboardMarkup()
        bt1 = types.KeyboardButton('Москва')
        bt2 = types.KeyboardButton('Санкт-Петербург')
        bt3 = types.KeyboardButton('Нижний Новгород')
        bt4= types.KeyboardButton('Пермь')
        markup.add(bt1,bt2,bt3,bt4)
        bot.send_message(message.chat.id,'В каком городе ты собираешься поступать?',reply_markup=markup)
    if message.text == 'Москва':
        markup = types.ReplyKeyboardMarkup()
        bt1 = types.KeyboardButton('МАТЕМАТИКА, ФИЗИКА, ХИМИЯ, ГЕОГРАФИЯ, БИОЛОГИЯ')
        bt2 = types.KeyboardButton('КОМПЬЮТЕРНЫЕ НАУКИ')
        bt3 = types.KeyboardButton('ИНЖЕНЕРНЫЕ И ТЕХНИЧЕСКИЕ НАУКИ')
        bt4= types.KeyboardButton('КОММУНИКАЦИИ, МЕДИА И ДИЗАЙН')
        bt5 = types.KeyboardButton('ЭКОНОМИКА')
        bt6 = types.KeyboardButton('УПРАВЛЕНИЕ')
        bt7 = types.KeyboardButton('ЮРИCПРУДЕНЦИЯ')
        bt8 = types.KeyboardButton('АРХИТЕКТУРА')
        bt9 = types.KeyboardButton('АКТЕРСКОЕ ИСКУССТВО')
        bt10 = types.KeyboardButton('ГУМАНИТАРНЫЕ НАУКИ')
        bt11 = types.KeyboardButton('СОЦИАЛЬНЫЕ НАУКИ')
        markup.add(bt1,bt2,bt3,bt4,bt5,bt6,bt7,bt8,bt9,bt10,bt11)
        bot.send_message(message.chat.id,'А теперь определись с факультетом!',reply_markup=markup)
    elif message.text =='Санкт-Петербург':
        markup = types.ReplyKeyboardMarkup()
        bt1 = types.KeyboardButton('ЭКОНОМИКА И УПРАВЛЕНИЕ')
        bt2 = types.KeyboardButton('ГОСУДАРСТВЕННОЕ И МУНИЦИПАЛЬНОЕ УПРАВЛЕНИЕ')
        bt3 = types.KeyboardButton('ФИЗИКА')
        bt4 = types.KeyboardButton('КОМПЬЮТЕРНЫЕ НАУКИ')
        bt5 = types.KeyboardButton('ЮРИСПРУДЕНЦИЯ')
        bt6 = types.KeyboardButton('ГУМАНИТАРНЫЕ НАУКИ')
        bt7 = types.KeyboardButton('СОЦИАЛЬНЫЕ НАУКИ')
        bt8 = types.KeyboardButton('КОММУНИКАЦИИ, МЕДИА И ДИЗАЙН')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6, bt7, bt8)
        bot.send_message(message.chat.id, 'А теперь определись с факультетом!', reply_markup=markup)
    elif message.text =='Нижний Новгород':
        markup = types.ReplyKeyboardMarkup()
        bt1 = types.KeyboardButton('МАТЕМАТИКА')
        bt2 = types.KeyboardButton('КОМПЬЮТЕРНЫЕ НАУКИ')
        bt3 = types.KeyboardButton('КОММУНИКАЦИИ, МЕДИА И ДИЗАЙН')
        bt4 = types.KeyboardButton('ЭКОНОМИКА И МЕНЕДЖМЕНТ')
        bt5 = types.KeyboardButton('ЮРИСПРУДЕНЦИЯ')
        bt6 = types.KeyboardButton('ГУМАНИТАРНЫЕ НАУКИ')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6)
        bot.send_message(message.chat.id, 'А теперь определись с факультетом!', reply_markup=markup)
    elif message.text =='Пермь':
        markup = types.ReplyKeyboardMarkup()
        bt1 = types.KeyboardButton('КОМПЬЮТЕРНЫЕ НАУКИ')
        bt2 = types.KeyboardButton('ЭКОНОМИКА И УПРАВЛЕНИЕ')
        bt3 = types.KeyboardButton('КОММУНИКАЦИИ, МЕДИА И ДИЗАЙН')
        bt4 = types.KeyboardButton('ЮРИСПРУДЕНЦИЯ')
        bt5 = types.KeyboardButton('ГУМАНИТАРНЫЕ НАУКИ')
        markup.add(bt1, bt2, bt3, bt4, bt5)
        bot.send_message(message.chat.id, 'А теперь определись с факультетом!', reply_markup=markup)
    if message.text == 'МАТЕМАТИКА, ФИЗИКА, ХИМИЯ, ГЕОГРАФИЯ, БИОЛОГИЯ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('География глобальных изменений и геоинформационные технологии',url='https://www.hse.ru/ba/geography/')
        bt2 = types.InlineKeyboardButton('Математика',url='https://www.hse.ru/ba/math/')
        bt3 = types.InlineKeyboardButton('Совместный бакалавриат НИУ ВШЭ и ЦПМ', url='https://www.hse.ru/ba/cpm/')
        bt4 = types.InlineKeyboardButton('Физика', url='https://www.hse.ru/ba/physics/')
        bt5 = types.InlineKeyboardButton('Химия', url='https://www.hse.ru/ba/chem/')
        bt6 = types.InlineKeyboardButton('Клеточная и молекулярная биотехнология', url='https://www.hse.ru/ba/cmb/')
        bt7 = types.InlineKeyboardButton('Когнитивная нейробиология', url='https://www.hse.ru/ba/neuroscience/')
        markup.add(bt1,bt2,bt3,bt4,bt5,bt6,bt7)
        bot.send_message(message.chat.id,'Лови ссылки на образовательные программы!',reply_markup=markup)
    elif message.text == 'КОМПЬЮТЕРНЫЕ НАУКИ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Прикладная математика и информатика',url='https://www.hse.ru/ba/ami/')
        bt2 = types.InlineKeyboardButton('Программная инженерия', url='https://www.hse.ru/ba/se/')
        bt3 = types.InlineKeyboardButton('Прикладной анализ данных', url='https://www.hse.ru/ba/data/')
        bt4 = types.InlineKeyboardButton('Компьютерные науки и анализ данных', url='https://www.hse.ru/ba/compds/')
        markup.add(bt1, bt2, bt3, bt4)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ИНЖЕНЕРНЫЕ И ТЕХНИЧЕСКИЕ НАУКИ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Инфокоммуникационные технологии и системы связи', url='https://www.hse.ru/ba/it/')
        bt2 = types.InlineKeyboardButton('Информатика и вычислительная техника', url='https://www.hse.ru/ba/isct/')
        bt3 = types.InlineKeyboardButton('Информационная безопасность', url='https://www.hse.ru/ba/is/')
        bt4 = types.InlineKeyboardButton('Компьютерная безопасность', url='https://www.hse.ru/ba/cosec/?roistat_visit=7670128')
        bt5 = types.InlineKeyboardButton('Прикладная математика', url='https://www.hse.ru/ba/am/?roistat_visit=7670128')
        markup.add(bt1, bt2, bt3, bt4, bt5)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'КОММУНИКАЦИИ, МЕДИА И ДИЗАЙН':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Дизайн',url='https://www.hse.ru/ba/design/')
        bt2 = types.InlineKeyboardButton('Журналистика', url='https://www.hse.ru/ba/journ/')
        bt3 = types.InlineKeyboardButton('Кинопроизводство', url='https://www.hse.ru/ba/film/')
        bt4 = types.InlineKeyboardButton('Медиакоммуникации', url='https://www.hse.ru/ba/media/')
        bt5 = types.InlineKeyboardButton('Мода', url='https://www.hse.ru/ba/moda/')
        bt6 = types.InlineKeyboardButton('Реклама и связи с общественностью', url='https://www.hse.ru/ba/ad/')
        bt7 = types.InlineKeyboardButton('Современное искусство', url='https://www.hse.ru/ba/art/')
        bt8 = types.InlineKeyboardButton('Стратегия и продюсирование в коммуникациях', url='https://www.hse.ru/ba/producer/')
        bt9 = types.InlineKeyboardButton('Управление в креативных индустриях', url='https://www.hse.ru/ba/creative/')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6, bt7,bt8,bt9)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ЭКОНОМИКА':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Мировая экономика', url='https://www.hse.ru/ba/we/')
        bt2 = types.InlineKeyboardButton('Международная программа по экономике и финансам', url='https://www.hse.ru/ba/icef/')
        bt3 = types.InlineKeyboardButton('Совместная программа по экономике НИУ ВШЭ и РЭШ', url='https://www.hse.ru/ba/nes/?roistat_visit=7670128')
        bt4 = types.InlineKeyboardButton('Экономика', url='https://www.hse.ru/ba/economics/')
        bt5 = types.InlineKeyboardButton('Экономика и анализ данных', url='https://www.hse.ru/ba/eda/')
        bt6 = types.InlineKeyboardButton('Экономика и статистика', url='https://www.hse.ru/ba/stat/')
        bt7 = types.InlineKeyboardButton('Экономический анализ', url='https://www.hse.ru/ba/ea/')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6, bt7)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)

    elif message.text == 'УПРАВЛЕНИЕ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Бизнес-информатика', url='https://www.hse.ru/ba/bi/')
        bt2 = types.InlineKeyboardButton('Государственное и муниципальное управление', url='https://www.hse.ru/ba/gmu/')
        bt3 = types.InlineKeyboardButton('Маркетинг и рыночная аналитика',url='https://www.hse.ru/ba/marketing/')
        bt4 = types.InlineKeyboardButton('Международный бизнес', url='https://www.hse.ru/ba/ib/')
        bt5 = types.InlineKeyboardButton('Управление бизнесом', url='https://www.hse.ru/ba/bba/')
        bt6 = types.InlineKeyboardButton('Управление цепями поставок и бизнес-аналитика', url='https://www.hse.ru/ba/logistics/')
        bt7 = types.InlineKeyboardButton('Цифровые инновации в управлении предприятием', url='https://www.hse.ru/ba/digital/')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6, bt7)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)

    elif message.text == 'ЮРИCПРУДЕНЦИЯ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Право', url='https://www.hse.ru/ba/law/')
        bt2 = types.InlineKeyboardButton('Цифровой юрист', url='https://www.hse.ru/ba/dlawyer/')
        markup.add(bt1, bt2)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'АРХИТЕКТУРА':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Городское планирование', url='https://www.hse.ru/ba/up/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)

    elif message.text == 'АКТЕРСКОЕ ИСКУССТВО':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Актер', url='https://www.hse.ru/ba/actor/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ГУМАНИТАРНЫЕ НАУКИ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Античность', url='https://www.hse.ru/ba/antiq/')
        bt2 = types.InlineKeyboardButton('Библеистика и история древнего Израиля', url='https://www.hse.ru/ba/israel/')
        bt3 = types.InlineKeyboardButton('Востоковедение', url='https://www.hse.ru/ba/oriental/')
        bt4 = types.InlineKeyboardButton('Иностранные языки и межкультурная коммуникация', url='https://www.hse.ru/ba/lang/')
        bt5 = types.InlineKeyboardButton('История', url='https://www.hse.ru/ba/hist/')
        bt6 = types.InlineKeyboardButton('История искусств', url='https://www.hse.ru/ba/histart/')
        bt7 = types.InlineKeyboardButton('Культурология', url='https://www.hse.ru/ba/cultural/')
        bt8 = types.InlineKeyboardButton('Филология',url='https://www.hse.ru/ba/philology/')
        bt9 = types.InlineKeyboardButton('Философия', url='https://www.hse.ru/ba/phil/')
        bt10 = types.InlineKeyboardButton('Фундаментальная и компьютерная лингвистика', url='https://www.hse.ru/ba/ling/')
        bt11 = types.InlineKeyboardButton('Язык и литература Ирана', url='https://www.hse.ru/ba/iran/')
        bt12 = types.InlineKeyboardButton('Языки и литература Индии', url='https://www.hse.ru/ba/india/')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6, bt7, bt8, bt9,bt10,bt11,bt12)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)

    elif message.text == 'СОЦИАЛЬНЫЕ НАУКИ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Международные отношения', url='https://www.hse.ru/ba/ia/')
        bt2 = types.InlineKeyboardButton('Международная программа «Международные отношения и глобальные исследования»', url='https://www.hse.ru/ba/ir/')
        bt3 = types.InlineKeyboardButton('Программа двух дипломов НИУ ВШЭ и Университета Кёнхи «Экономика и политика в Азии»', url='https://www.hse.ru/ba/epa/')
        bt4 = types.InlineKeyboardButton('Политология',url='https://www.hse.ru/ba/political/')
        bt5 = types.InlineKeyboardButton('Психология', url='https://www.hse.ru/ba/psy/')
        bt6 = types.InlineKeyboardButton('Социология', url='https://www.hse.ru/ba/soc/')
        markup.add(bt1, bt2, bt3, bt4, bt5, bt6)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ЭКОНОМИКА И УПРАВЛЕНИЕ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Международный бакалавриат по бизнесу и экономике', url='https://spb.hse.ru/ba/interbac/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ГОСУДАРСТВЕННОЕ И МУНИЦИПАЛЬНОЕ УПРАВЛЕНИЕ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Управление и аналитика в государственном секторе', url='https://spb.hse.ru/ba/gmu/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ФИЗИКА':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Физика', url='https://spb.hse.ru/ba/physics/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ЮРИСПРУДЕНЦИЯ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Юриспруденция', url='https://spb.hse.ru/ba/law/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'ЭКОНОМИКА И МЕНЕДЖМЕНТ':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Цифровой маркетинг', url='https://nnov.hse.ru/ba/dm/')
        bt2 = types.InlineKeyboardButton('Международный бакалавриат по бизнесу и экономике', url='https://nnov.hse.ru/ba/interbac/')
        markup.add(bt1,bt2)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)
    elif message.text == 'МАТЕМАТИКА':
        markup = types.InlineKeyboardMarkup()
        bt1 = types.InlineKeyboardButton('Математика', url='https://nnov.hse.ru/ba/math/')
        markup.add(bt1)
        bot.send_message(message.chat.id, 'Лови ссылки на образовательные программы!', reply_markup=markup)

    


bot.infinity_polling()


